//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Compamy
    {
        public int Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string Name { get; set; }
        public string User_Login { get; set; }
        public string User_Password { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
