name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: mcr.microsoft.com/dotnet/sdk:5.0.102-ca-patch-buster-slim

    steps:
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        DOTNET_VERSION: net5.0
        TEST_PROJECT_NAME: Cryptography.Tests
        PATH_TO_ASSEMBLY: bin/Debug/$DOTNET_VERSION
      run: |
        export PATH="$PATH:/root/.dotnet/tools"
        dotnet tool install --global coverlet.console
        coverlet "./$TEST_PROJECT_NAME/$PATH_TO_ASSEMBLY/$TEST_PROJECT_NAME.dll" --target "dotnet" --targetargs "test ./$TEST_PROJECT_NAME/$TEST_PROJECT_NAME.csproj --no-build" --merge-with ./coverage.json
        dotnet test --no-build --verbosity normal
